//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_CRUD_Application_Demo.Report {
    
    
    public partial class EmployeeList {
        
        /// <summary>
        /// ucrvBondList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::MVC_CRUD_Application_Demo.Report.ucReportViewer ucrvBondList;
    }
}
